version: "2"

networks:
    docker_zeebe_network:
        external: true
        
services: 
    zeebe_nodejs:
        container_name: zeebe_nodejs
        build:
            context: ./
        volumes:
            - ./:/app/
            - /app/node_modules
        networks:
            - docker_zeebe_network
