version: "3.8"
        
services: 
    scooter_web_api:
        container_name: scooter_web_api
        build:
            context: ./
        ports:
            - "8090:8090"
        volumes:
            - ./:/app/
            - /app/node_modules
