version: "2"

networks:
    zeebe_network:

volumes:
    data:
    n_modules:

services:
    zeebe:
        image: camunda/zeebe:0.24.1
        environment:
            - ZEEBE_LOG_LEVEL=debug
        ports:
            - "26500:26500"
            - "9600:9600"
        volumes:
            - data:/usr/local/zeebe/data
            - ./broker_embedded_gateway.yml:/usr/local/zeebe/config/application.yaml
        depends_on:
            - elasticsearch
        networks:
            - zeebe_network
        container_name: zeebe

    operate:
        image: camunda/operate:0.24.2
        ports:
            - "8080:8080"
        depends_on:
            - zeebe
            - elasticsearch
        volumes:
            - ./operate.yml:/usr/local/operate/config/application.yml
        networks:
            - zeebe_network
        container_name: operate

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
            - cluster.name=elasticsearch
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        networks:
            - zeebe_network
        container_name: elasticsearch


    scooter_web_api:
        container_name: scooter_web_api
        build:
            context: ../.lib/scooter-web-api/
        ports:
            - "8090:8090"
        volumes:
            - ./../.lib/scooter-web-api/:/app/
            - n_modules:/app/node_modules
        networks:
            - zeebe_network
        depends_on:
            - zeebe
            - elasticsearch
            - operate
